Repository prgrms-web-devcourse-final-project/WEB6_8_HaeDokCoding_BE, pull requests merged in 2025-10, with the labels that each got.

#209 [test] ProfileController 테스트 코드 추가 #204
  src/main/java/com/back/domain/post/comment/service/CommentService.java
  src/test/java/com/back/domain/profile/controller/ProfileControllerTest.java
Labels: test

#211 [feat] 단계별 추천 추가 및 '전체' 옵션 추가 #199
  src/main/java/com/back/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/back/domain/chatbot/dto/ChatResponseDto.java
  src/main/java/com/back/domain/chatbot/enums/MessageType.java
  src/main/java/com/back/domain/chatbot/repository/ChatConversationRepository.java
  src/main/java/com/back/domain/chatbot/service/ChatbotService.java
Labels: feat

#213 [fix] 전체 옵션 오류 해결 #212
  src/main/java/com/back/domain/chatbot/dto/ChatRequestDto.java
  src/main/java/com/back/domain/chatbot/service/ChatbotService.java
Labels: fix

#217 [feat] 프로필 상단 카드 요약에 '킵한 칵테일 수' 집계 구현 #210
  src/main/java/com/back/domain/profile/dto/ProfileResponseDto.java
  src/main/java/com/back/domain/profile/service/ProfileService.java
  src/test/java/com/back/domain/profile/controller/ProfileControllerTest.java
Labels: feat

#220 [test] NotificationController의 알림 관련 기능 통합 테스트 추가 #218
  src/test/java/com/back/domain/notification/controller/NotificationControllerTest.java
Labels: test

#224 [fix] 댓글 수정/삭제 500 오류 해결 #222
  src/main/java/com/back/domain/post/comment/service/CommentService.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
Labels: fix

#226 [fix] aws설정 dev -> main yml로 변경 (CICD test)
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: fix

#228 [fix] chatbot 도메인 currentStep 관련 문제 해결 #227
  src/main/java/com/back/domain/chatbot/dto/ChatRequestDto.java
  src/main/java/com/back/domain/chatbot/service/ChatbotService.java
Labels: fix

#231 [fix] 삭제된 댓글이 조회되는 오류 해결 #230
  src/main/java/com/back/domain/post/comment/repository/CommentRepository.java
  src/main/java/com/back/domain/post/comment/service/CommentService.java
Labels: fix

#233 [chore] 불필요한 수정 되돌리기 #230
  src/main/java/com/back/domain/post/comment/repository/CommentRepository.java
  src/main/java/com/back/domain/post/comment/service/CommentService.java
Labels: chore

#235 [refactor] 챗봇 - 응답구조 통일 #234
  src/main/java/com/back/domain/chatbot/dto/ChatResponseDto.java
  src/main/java/com/back/domain/chatbot/service/ChatbotService.java
Labels: refactor

#238 [feat] 챗봇 - input 추가 및 마지막 단계 삭제 #236
  src/main/java/com/back/domain/chatbot/dto/ChatRequestDto.java
  src/main/java/com/back/domain/chatbot/enums/MessageType.java
  src/main/java/com/back/domain/chatbot/service/ChatbotService.java
Labels: feat

#244 [fix] 삭제된 댓글 필터링, 조회수 증가 로직 버그 수정#243
  src/main/java/com/back/domain/post/comment/repository/CommentRepository.java
  src/main/java/com/back/domain/post/comment/service/CommentService.java
  src/main/java/com/back/domain/post/post/service/PostService.java
Labels: fix
