Repository prgrms-web-devcourse-final-project/WEB6_8_HaeDokCoding_BE, pull requests merged in 2025-09, with the labels that each got.

#5 [chore] 코드래빗 관련 이슈 자동할당 & pr 자동화 설정#1
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/autoIssue.yml
  .github/workflows/autoPR.yml
  db_dev.mv.db
Labels: chore

#6 [feat] 스타터 킷 설정#1
  build.gradle.kts
  src/main/java/com/back/BackApplication.java
  src/main/java/com/back/global/appConfig/AppConfig.java
  src/main/java/com/back/global/appConfig/JpaAuditingConfig.java
  src/main/java/com/back/global/appConfig/SwaggerConfig.java
  src/main/java/com/back/global/aspect/ResponseAspect.java
  src/main/java/com/back/global/controller/HomeController.java
  src/main/java/com/back/global/exception/ServiceException.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/back/global/init/DevInitData.java
  src/main/java/com/back/global/init/TestInitData.java
  src/main/java/com/back/global/rsData/RsData.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: feat

#3 [chore] Issue 템플릿 추가
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
Labels: chore

#10 [fix] issue 템플릿에 YAML front matter 추가
  .github/ISSUE_TEMPLATE/basic.md
Labels: fix

#11 [feat] User 도메인 추가#7
  src/main/java/com/back/domain/user/dto/UserDto.java
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/domain/user/repository/UserRepository.java
Labels: feat

#15 [feat] cocktail엔티티, 리포지토리, DTO 추가 #9
  db_dev.mv.db
  src/main/java/com/back/domain/cocktail/dto/CocktailRequestDto.java
  src/main/java/com/back/domain/cocktail/dto/CocktailResponseDto.java
  src/main/java/com/back/domain/cocktail/entity/Cocktail.java
  src/main/java/com/back/domain/cocktail/repository/CocktailRepository.java
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/domain/wishlist/entity/Wishlist.java
Labels: feat

#18 [feat] Security Config설정, CustomAuthenticationFilter 설정#1
  .gitignore
  build.gradle.kts
  db_dev.mv.db
  src/main/java/com/back/domain/user/dto/UserDto.java
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/global/jwt/JwtUtil.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/main/java/com/back/global/standard/util/Ut.java
  src/main/resources/application.yml
Labels: feat

#20 [feat] 프로필 조회 기능 구현 #16
  src/main/java/com/back/domain/profile/controller/ProfileController.java
  src/main/java/com/back/domain/profile/dto/ProfileResponseDto.java
  src/main/java/com/back/domain/profile/service/ProfileService.java
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/domain/user/repository/UserRepository.java
  src/main/java/com/back/domain/user/support/AbvView.java
Labels: feat

#22 [feat] 프로필 수정 기능 구현 #21
  build.gradle.kts
  src/main/java/com/back/domain/profile/controller/ProfileController.java
  src/main/java/com/back/domain/profile/dto/ProfileUpdateRequestDto.java
  src/main/java/com/back/domain/profile/service/ProfileService.java
Labels: feat

#29 [feat] 나만의 Bar(킵) 목록 조회 기능 구현 #23
  src/main/java/com/back/domain/mybar/controller/MyBarController.java
  src/main/java/com/back/domain/mybar/dto/MyBarItemResponseDto.java
  src/main/java/com/back/domain/mybar/dto/MyBarListResponseDto.java
  src/main/java/com/back/domain/mybar/entity/MyBar.java
  src/main/java/com/back/domain/mybar/enums/KeepStatus.java
  src/main/java/com/back/domain/mybar/repository/MyBarRepository.java
  src/main/java/com/back/domain/mybar/service/MyBarService.java
  src/main/java/com/back/domain/wishlist/dto/WishlistRequestDto.java
  src/main/java/com/back/domain/wishlist/dto/WishlistResponseDto.java
  src/main/java/com/back/domain/wishlist/entity/Wishlist.java
  src/main/java/com/back/domain/wishlist/enums/WishlistStatus.java
  src/main/java/com/back/domain/wishlist/repository/WishlistRepository.java
Labels: feat

#32 [feat] 칵테일 조회 및 검색 기능 구현
  .gitignore
  src/main/java/com/back/domain/cocktail/dto/CocktailRequestDto.java
  src/main/java/com/back/domain/cocktail/dto/CocktailResponseDto.java
  src/main/java/com/back/domain/cocktail/dto/CocktailSummaryDto.java
  src/main/java/com/back/domain/cocktail/entity/Cocktail.java
  src/main/java/com/back/domain/cocktail/enums/AlcoholBaseType.java
  src/main/java/com/back/domain/cocktail/enums/AlcoholStrength.java
  src/main/java/com/back/domain/cocktail/enums/CocktailType.java
  src/main/java/com/back/domain/cocktail/repository/CocktailRepository.java
  src/main/java/com/back/domain/cocktail/service/CocktailService.java
  src/main/java/com/back/domain/mybar/dto/MyBarItemResponseDto.java
  src/main/java/com/back/global/init/DevInitData.java
Labels: feat

#33 [feat] 나만의 bar(킵) 추가/재추가 기능 구현 #30
  src/main/java/com/back/domain/mybar/controller/MyBarController.java
  src/main/java/com/back/domain/mybar/dto/MyBarItemResponseDto.java
  src/main/java/com/back/domain/mybar/entity/MyBar.java
  src/main/java/com/back/domain/mybar/repository/MyBarRepository.java
  src/main/java/com/back/domain/mybar/service/MyBarService.java
Labels: feat

#38 [refactor] AbvLevel Enum의 L1 등급 기준 및 로직 변경 #37
  src/main/java/com/back/domain/user/enums/AbvLevel.java
Labels: refactor

#50 [feat] 게시글 단건 조회 구현#44
  src/main/java/com/back/domain/post/post/controller/PostController.java
  src/main/java/com/back/domain/post/post/service/PostService.java
Labels: feat

#51 [refactor] 나만의 bar 페이지네이션을 커서 기반으로 리팩토링 #49
  src/main/java/com/back/domain/mybar/controller/MyBarController.java
  src/main/java/com/back/domain/mybar/dto/MyBarListResponseDto.java
  src/main/java/com/back/domain/mybar/repository/MyBarRepository.java
  src/main/java/com/back/domain/mybar/service/MyBarService.java
Labels: refactor

#52 [feat] Redis 로컬 실행을 위한 docker-compose.yml 작성
  docker-compose.yml
Labels: feat

#54 [feat] 게시글 수정 구현#45
  src/main/java/com/back/domain/post/post/controller/PostController.java
  src/main/java/com/back/domain/post/post/dto/request/PostCreateRequestDto.java
  src/main/java/com/back/domain/post/post/dto/request/PostUpdateRequestDto.java
  src/main/java/com/back/domain/post/post/entity/Post.java
  src/main/java/com/back/domain/post/post/service/PostService.java
Labels: feat

#55 [feat] 게시글 삭제 구현#46
  src/main/java/com/back/domain/post/post/controller/PostController.java
  src/main/java/com/back/domain/post/post/service/PostService.java
Labels: feat

#99 [fix] 백엔드 배포환경 url 수정
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: fix

#100 [feat] 알림 설정 조회 및 on/off 기능 구현 #89
  src/main/java/com/back/domain/notification/controller/NotificationController.java
  src/main/java/com/back/domain/notification/dto/NotificationSettingDto.java
  src/main/java/com/back/domain/notification/dto/NotificationSettingUpdateRequestDto.java
  src/main/java/com/back/domain/notification/entity/NotificationSetting.java
  src/main/java/com/back/domain/notification/repository/NotificationSettingRepository.java
  src/main/java/com/back/domain/notification/service/NotificationSettingService.java
Labels: feat

#105 [feat] 게시글 추천 기능 구현#102
  src/main/java/com/back/domain/post/comment/controller/CommentController.java
  src/main/java/com/back/domain/post/post/controller/PostController.java
  src/main/java/com/back/domain/post/post/entity/Post.java
  src/main/java/com/back/domain/post/post/entity/PostLike.java
  src/main/java/com/back/domain/post/post/enums/PostLikeStatus.java
  src/main/java/com/back/domain/post/post/repository/PostLikeRepository.java
  src/main/java/com/back/domain/post/post/service/PostService.java
  src/main/java/com/back/domain/user/entity/User.java
Labels: feat

#107 [refactor] 카카오 리다이렉트 url 매핑 수정 & 배포 설정 변경
  src/main/java/com/back/domain/notification/controller/NotificationController.java
  src/main/java/com/back/domain/notification/dto/NotificationSettingDto.java
  src/main/java/com/back/domain/notification/dto/NotificationSettingUpdateRequestDto.java
  src/main/java/com/back/domain/notification/entity/NotificationSetting.java
  src/main/java/com/back/domain/notification/repository/NotificationSettingRepository.java
  src/main/java/com/back/domain/notification/service/NotificationSettingService.java
  src/main/java/com/back/global/jwt/refreshToken/service/RefreshTokenService.java
  src/main/java/com/back/global/security/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: refactor

#111 [feat] AI 챗봇 프롬포트 엔지니어링 #83
  src/main/java/com/back/domain/chatbot/dto/GeminiRequestDto.java
  src/main/java/com/back/domain/chatbot/service/ChatbotService.java
  src/main/java/com/back/domain/chatbot/service/GeminiApiService.java
  src/main/resources/application.yml
  src/main/resources/prompts/chatbot-response-rules.txt
  src/main/resources/prompts/chatbot-system-prompt.txt
Labels: feat

#109 [feat] 칵테일 댓글 도메인작업 & 칵테일 id 수정#91
  src/main/java/com/back/domain/cocktail/comment/dto/CocktailCommentCreateRequestDto.java
  src/main/java/com/back/domain/cocktail/comment/dto/CocktailCommentResponseDto.java
  src/main/java/com/back/domain/cocktail/comment/dto/CocktailCommentUpdateRequestDto.java
  src/main/java/com/back/domain/cocktail/comment/entity/CocktailComment.java
  src/main/java/com/back/domain/cocktail/comment/repository/CocktailCommentRepository.java
  src/main/java/com/back/domain/cocktail/controller/CocktailShareController.java
  src/main/java/com/back/domain/cocktail/dto/CocktailDetailResponseDto.java
  src/main/java/com/back/domain/cocktail/entity/Cocktail.java
  src/main/java/com/back/domain/cocktail/repository/CocktailRepository.java
  src/main/java/com/back/domain/cocktail/service/CocktailService.java
  src/main/java/com/back/domain/mybar/dto/MyBarItemResponseDto.java
  src/main/java/com/back/domain/mybar/repository/MyBarRepository.java
  src/main/java/com/back/domain/mybar/service/MyBarService.java
  src/test/java/com/back/domain/cocktail/controller/CocktailControllerTest.java
Labels: feat

#117 [feat] 닉네임 랜덤 생성, OAuth redirect 변경#112
  src/main/java/com/back/domain/cocktail/entity/Cocktail.java
  src/main/java/com/back/domain/user/dto/UserDto.java
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/domain/user/service/UserAuthService.java
  src/main/java/com/back/global/jwt/refreshToken/service/RefreshTokenService.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/CustomOAuth2LoginFailureHandler.java
  src/main/java/com/back/global/security/CustomOAuth2LoginSuccessHandler.java
  src/main/java/com/back/global/security/CustomOAuth2UserService.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat

#124 [feat]칵테일 댓글 CRUD
  src/main/java/com/back/domain/cocktail/comment/controller/CocktailCommentController.java
  src/main/java/com/back/domain/cocktail/comment/repository/CocktailCommentRepository.java
  src/main/java/com/back/domain/cocktail/comment/service/CocktailCommentService.java
  src/main/java/com/back/domain/cocktail/controller/CocktailController.java
  src/main/java/com/back/domain/cocktail/entity/Cocktail.java
Labels: feat

#129 [refactor] 사용하지 않는 imagePath 필드 제거
  src/main/java/com/back/domain/user/dto/UserDto.java
  src/main/java/com/back/domain/user/enums/AbvLevel.java
Labels: refactor

#132 [refactor] Spring Ai 구현방식으로 리팩토링 #114
  build.gradle.kts
  src/main/java/com/back/domain/chatbot/dto/GeminiRequestDto.java
  src/main/java/com/back/domain/chatbot/dto/GeminiResponseDto.java
  src/main/java/com/back/domain/chatbot/service/ChatbotService.java
  src/main/java/com/back/domain/chatbot/service/GeminiApiService.java
  src/main/java/com/back/global/appConfig/GeminiConfig.java
  src/main/resources/application.yml
Labels: refactor

#133 [feat] 신규 사용자 abvDegree 기본값 처리 로직 추가 #131
  src/main/java/com/back/domain/profile/dto/ProfileResponseDto.java
Labels: feat

#139 [feat] 게시글 영상 업로드 기능 구현#127
  src/main/java/com/back/domain/post/post/dto/request/PostCreateRequestDto.java
  src/main/java/com/back/domain/post/post/dto/request/PostUpdateRequestDto.java
  src/main/java/com/back/domain/post/post/dto/response/PostResponseDto.java
  src/main/java/com/back/domain/post/post/entity/Post.java
  src/main/java/com/back/domain/post/post/service/PostService.java
Labels: feat

#141 [refactor] api 접두사 제거 및 개발용 security 설정#138
  Dockerfile
  src/main/java/com/back/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/back/domain/cocktail/comment/controller/CocktailCommentController.java
  src/main/java/com/back/domain/cocktail/controller/CocktailController.java
  src/main/java/com/back/domain/cocktail/controller/CocktailShareController.java
  src/main/java/com/back/domain/mybar/controller/MyBarController.java
  src/main/java/com/back/domain/myhistory/controller/MyHistoryController.java
  src/main/java/com/back/domain/myhistory/service/MyHistoryService.java
  src/main/java/com/back/domain/notification/controller/NotificationController.java
  src/main/java/com/back/domain/notification/service/NotificationService.java
  src/main/java/com/back/domain/post/comment/controller/CommentController.java
  src/main/java/com/back/domain/post/post/controller/PostController.java
  src/main/java/com/back/domain/profile/controller/ProfileController.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/test/java/com/back/domain/cocktail/controller/CocktailControllerTest.java
Labels: refactor

#142 [chore] 개발 환경 ddl-auto 설정 바꾸고 다시 테스트#137
  src/main/java/com/back/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/back/domain/cocktail/comment/controller/CocktailCommentController.java
  src/main/java/com/back/domain/cocktail/controller/CocktailController.java
  src/main/java/com/back/domain/cocktail/controller/CocktailShareController.java
  src/main/java/com/back/domain/mybar/controller/MyBarController.java
  src/main/java/com/back/domain/myhistory/controller/MyHistoryController.java
  src/main/java/com/back/domain/myhistory/service/MyHistoryService.java
  src/main/java/com/back/domain/notification/controller/NotificationController.java
  src/main/java/com/back/domain/notification/service/NotificationService.java
  src/main/java/com/back/domain/post/comment/controller/CommentController.java
  src/main/java/com/back/domain/post/post/controller/PostController.java
  src/main/java/com/back/domain/profile/controller/ProfileController.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/resources/application-prod.yml
  src/test/java/com/back/domain/cocktail/controller/CocktailControllerTest.java
Labels: fix, chore

#145 [chore] 예약어? 제외한 @Table name어노테이션 제거#137
  src/main/java/com/back/domain/cocktail/comment/entity/CocktailComment.java
  src/main/java/com/back/domain/post/category/entity/Category.java
  src/main/java/com/back/domain/post/comment/entity/Comment.java
  src/main/java/com/back/domain/post/post/dto/request/PostCreateRequestDto.java
  src/main/java/com/back/domain/post/post/dto/request/PostUpdateRequestDto.java
  src/main/java/com/back/domain/post/post/dto/response/PostResponseDto.java
  src/main/java/com/back/domain/post/post/entity/Post.java
  src/main/java/com/back/domain/post/post/entity/PostLike.java
  src/main/java/com/back/domain/post/post/entity/PostTag.java
  src/main/java/com/back/domain/post/post/entity/Tag.java
  src/main/java/com/back/domain/post/post/service/PostService.java
Labels: fix, chore

#159 [feat] 유사칵테일 추천 기능 구현
  src/main/java/com/back/domain/cocktail/controller/CocktailRecommendController.java
  src/main/java/com/back/domain/cocktail/dto/CocktailRecommendResponseDto.java
  src/main/java/com/back/domain/cocktail/repository/CocktailRepository.java
  src/main/java/com/back/domain/cocktail/service/RecommendService.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/resources/data-h2.sql
Labels: feat

#162 [feat] 개발 환경 초기 데이터 구성(DevInitData) #158
  src/main/java/com/back/global/init/DevInitData.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/resources/static/img/cocktail/1.jpg
  src/main/resources/static/img/cocktail/2.jpg
  src/main/resources/static/img/cocktail/3.jpg
  src/main/resources/static/img/cocktail/4.jpg
Labels: feat, chore

#167 [test] PostControllerTest 구현#165
  src/test/java/com/back/domain/post/post/controller/PostControllerTest.java
Labels: feat, test

#168 hotfix:오류 수정
  src/main/java/com/back/domain/user/entity/User.java
  src/main/java/com/back/global/init/DevInitData.java
Labels: fix

#170 [fix] FE에 발생한 AWS region 설정 문제 해결 #169
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: fix

#196 [fix] 쿠키 검증 실패로 크로스도메인 공유 해제#194
  src/main/resources/application-prod.yml
Labels: fix

#198 [refactor] 챗봇 엔티티 구조 수정 및 프롬포트 조정#176
  src/main/java/com/back/domain/chatbot/controller/ChatbotController.java
  src/main/java/com/back/domain/chatbot/dto/SaveBotMessageDto.java
  src/main/java/com/back/domain/chatbot/entity/ChatConversation.java
  src/main/java/com/back/domain/chatbot/enums/MessageSender.java
  src/main/java/com/back/domain/chatbot/repository/ChatConversationRepository.java
  src/main/java/com/back/domain/chatbot/service/ChatbotService.java
Labels: refactor

#200 [test] spring security test 작성
  src/main/java/com/back/domain/cocktail/controller/CocktailShareController.java
  src/main/java/com/back/global/jwt/JwtUtil.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/back/global/security/SecurityIntegrationTest.java
  src/test/resources/application-test.yml
  terraform/variables.tf
Labels: test
